- name: Provision instances in AWS
  hosts: "{{ lcl }}"
  connection: local
  gather_facts: False

  vars_files:
    - group_vars/all
    - group_vars/ec2

  tasks:
   - include: provision/ec2.yml
   - include: provision/elb.yml
