- name: Provision instances in AWS
  hosts: "{{ lcl }}"
  connection: local
  gather_facts: False

  # AWS variables from this group vars file
  vars_files:
    - group_vars/all
    - group_vars/ec2

  # Provisioning Tasks 
  tasks:
   - include: provision/ec2.yml

- name: Setup The Environment
  hosts: "tag_Stack_{{ rgn }}_{{ env }}_{{ app }}"
  become: True
  gather_facts: False

  vars_files:
   - group_vars/all
   - group_vars/ec2

  tasks:
   - include: setup/main.yml

- name: Provision instances in AWS
  hosts: "{{ lcl }}"
  connection: local
  gather_facts: False

  # AWS variables from this group vars file
  vars_files:
    - group_vars/all
    - group_vars/ec2

  # Provisioning Tasks
  tasks:
   - include: provision/elb.yml
