---
- name: Deploy The Application
  hosts: "tag_Stack_{{ rgn }}_{{ env }}_{{ app }}"
  become: True
  gather_facts: False

  vars_files:
   - group_vars/all
   - group_vars/ec2

  tasks:
   - include: setup/main.yml
   - include: setup/git.yml

  handlers: 
   - name: Restart Apache
     service: name=httpd state=restarted

- name: Load Balancer Tasks
  hosts: "{{ lcl }}"
  connection: local
  gather_facts: False

  vars_files:
   - group_vars/all
   - group_vars/ec2

  tasks:
   - include: setup/elb.yml
